### ISSUE TITLE
@stef Maybe path issue 

### ISSUE THREAD

**Issue by geekwise-estefania-flores** [geekwise-estefania-flores/django.drf.react.bank.project#1]
python 3.7 installed but when using Visual Studio code, showing 2.7.

I've tried reinstalling python 3 
when I run command as python3 --version, does show 3.7.4 
Also, won't let me use pip

@climateamante

**Comment by geekwise-estefania-flores** [comment]
<img width="568" alt="Screen Shot 2019-12-19 at 1 29 19 PM" src="https://user-images.githubusercontent.com/57374136/71211414-ed814480-2263-11ea-8cea-82a9fb2234a8.png">

**Comment by geekwise-estefania-flores** [comment]
<img width="801" alt="Screen Shot 2019-12-19 at 1 30 01 PM" src="https://user-images.githubusercontent.com/57374136/71211491-173a6b80-2264-11ea-935d-d71f64dabfd7.png">

**Comment by climateamante** [comment]
we did the thing - it happened.
