### ISSUE TITLE
issue deploying frontend to Heroku

### ISSUE THREAD

**Issue by geekwise-estefania-flores** [geekwise-estefania-flores/django.drf.react.bank.project#6]
I deleted everything from backend to deploy just the frontend to Heroku and got a buildpack issue. 
Had it when I first deployed the backend and it was the Procfile
<img width="928" alt="Screen Shot 2019-12-31 at 1 31 08 PM" src="https://user-images.githubusercontent.com/57374136/71634584-2b6e5900-2bd2-11ea-9f58-7cb7294ef847.png">

**Comment by geekwise-estefania-flores** [comment]
@climateamante @geekwise-korey-nichols @geekwise-yuki-xiong

**Comment by geekwise-yuki-xiong** [comment]
On your terminal do:
NOTE: you must have heroku cli installed
```
heroku login -i
heroku apps
heroku buildpacks:set heroku/nodejs -a your-heroku-project
```

**Comment by geekwise-estefania-flores** [comment]
<img width="797" alt="Screen Shot 2019-12-31 at 2 04 10 PM" src="https://user-images.githubusercontent.com/57374136/71635107-738f7a80-2bd6-11ea-812f-d62bf034442e.png">

Looks like it's a package.json issue now

**Comment by geekwise-yuki-xiong** [comment]
Find your node version with
```
node -v
```
Then add this code into your package.json list
```
"engines" : { 
      "node" : "your-node-verion-number"  
}
```

**Comment by geekwise-estefania-flores** [comment]
<img width="773" alt="Screen Shot 2019-12-31 at 2 36 50 PM" src="https://user-images.githubusercontent.com/57374136/71635626-016d6480-2bdb-11ea-81cc-2eea3ee65dbf.png">

**Comment by geekwise-korey-nichols** [comment]
try changing the file structure to this
![3](https://user-images.githubusercontent.com/57416695/71635643-18ac5200-2bdb-11ea-8eb1-c7602a0a433d.PNG)

currently your public folder is in frontend folder

**Comment by geekwise-yuki-xiong** [comment]
Keep only the node version and change your react-script version to 3.2.0

Also delete your package-lock.json, heroku will do the npm install on their end for you.
